# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for NetSentinel engine (Windows)."""

import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['app/main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'app.api.v1.router',
        'app.api.v1.discovery',
        'app.api.v1.port_scan',
        'app.api.v1.vulnerability',
        'app.api.v1.latency',
        'app.api.v1.system',
        'app.core.config',
        'app.core.logger',
        'app.models.discovery',
        'app.models.port_scan',
        'app.models.vulnerability',
        'app.models.latency',
        'app.services.discovery',
        'app.services.port_scanner',
        'app.services.vulnerability',
        'app.services.latency',
        'app.utils.oui',
        'scapy.arch',
        'scapy.arch.windows',
        'nmap',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'websockets',
        'websockets.legacy',
        'websockets.legacy.server',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'PIL',
        'cv2',
        'numpy',
        'pandas',
        'scipy',
        'zmq',
        'jupyter',
        'notebook',
        'IPython',
        'test',
        'unittest',
        'setuptools',
        'pkg_resources',
        'pip',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='netsentinel-engine',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traced=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
